### ISSUE TITLE
Getting a fatal error on the Abandoned Orders tab on clicking the "Abandoned Date" column title.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#1018]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have abandoned few carts and got the below error on clicking the "Abandoned Date" column title.

### Steps to reproduce

1. I have abandoned a few carts including the visitor carts, guest user, and logged-in user carts.
2. Then, I clicked on the "Abandoned Date" column title. And I got this error.

Fatal error: Uncaught TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, bool given in /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php:668 Stack trace: #0 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php(668): date_format() #1 [internal function]: WCAL_Abandoned_Orders_Table->wcal_class_order_date_asc() #2 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php(633): usort() #3 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php(79): WCAL_Abandoned_Orders_Table->wcal_abandoned_cart_data() #4 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php(2985): WCAL_Abandoned_Orders_Table->wcal_abandoned_order_prepare_items() #5 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): woocommerce_abandon_cart_lite->wcal_menu_page() #6 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #7 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #8 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-admin/admin.php(259): do_action() #9 {main} thrown in /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php on line 668

![2024-12-13_17-10-18](https://github.com/user-attachments/assets/32e61a23-7cd5-43ac-818e-2148fd0b001b)

### Expected behavior

Such an error should not appear from our plugin when clicking the "Abandoned Date" column title.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### Additional field

https://support.tychesoftwares.com/conversation/7483?folder_id=15

**Comment by mokshasharmila13** [comment]
The same error occurs for different lines in the code.

PHP Warning - 
PHP Warning: date_format() expects parameter 1 to be DateTimeInterface, bool given in /home/jopexakoba6547/web/cppwoo.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php on line 693

PHP Warning: date_format() expects parameter 1 to be DateTimeInterface, bool given in /home/jopexakoba6547/web/cppwoo.instawp.xyz/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/classes/class-wcal-abandoned-orders-table.php on line 688
