### ISSUE TITLE
Plugin throws me a database error when I try to add/edit the email template. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#843]
**Describe the bug**
Plugin throws me a database error when I try to add/edit the email template. 

**To Reproduce**
1. Go to Edit email template 
2. Try to add/edit the email template 
3. Plugin throw me a database error. https://www.screencast.com/t/z3piY0Gx

**Expected behavior**
No error must be thrown from our plugin.

**Comment by apeksha10** [comment]
With the latest git copy, I got a column but with a blank value.
https://www.screencast.com/t/JpjkjH4QvSr

Debug log error : 
[22-Aug-2022 09:49:29 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wpdb::update(), 2 passed in C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php on line 195 and at least 3 expected in C:\Users\User\Local Sites\local1\app\public\wp-includes\wp-db.php:2434
Stack trace:
#0 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(195): wpdb->update('wp_ac_email_tem...', Array)
#1 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(138): Wcal_Update::wcal_alter_tables('wp_', 0)
#2 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(85): Wcal_Update::wcal_process_db_update()
#3 C:\Users\User\Local Sites\local1\app\public\wp-includes\class-wp-hook.php(307): Wcal_Update::wcal_update_db_check()
#4 C:\Users\User\Local Sites\local1\app\public\wp-includes\class-wp-hook.php(331): WP_Hook->apply_fi in C:\Users\User\Local Sites\local1\app\public\wp-includes\wp-db.php on line 2434

Hence I have re-open this issue.

**Comment by apeksha10** [comment]
By mistake I have re-open this issue.
