### ISSUE TITLE
A fatal error received when I clicked checkout link from webhook.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#887]
**Describe the bug**
A fatal error received when I clicked checkout link from webhook.

**To Reproduce**
1. Upload the latest git copy 
2. Create webhook for cart abandoned and cart recoevered 
3. Clicked checkout link from webhook and open it to another browser. https://app.screencast.com/OF6JBfbHM8Kxj
4. The plugin throw me a fatal error. 

[05-Jun-2023 09:56:30 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php:1985
Stack trace:
#0 C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php(1950): woocommerce_abandon_cart_lite->wcal_load_guest_persistent_cart(63000010)
#1 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\class-wp-hook.php(308): woocommerce_abandon_cart_lite->wcal_email_track_links('C:\\Users\\User\\L...')
#2 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\plugin.php(205): WP_Hook->apply_filters('C:\\Users\\User\\L...', Array)
#3 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\template-loader.php(104): apply_filters('template_includ...', 'C:\\Users\\User\\L...')
#4 C:\Users\User\Local Sites\new-ui\app\public\wp-blog-header.php(19): require_once('C:\\Users\\User\\L...')
#5 C:\Users\User\Local Sites\new-ui\app\public\index.php(17): require('C:\\Users\\User\\L...')
#6 {main}
  thrown in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php on line 1985

Before updating the plugin (5.14.2 ) i followed the same above test case then to plugin throw me a fatal error.

Fatal error. [05-Jun-2023 09:50:05 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php:1950
Stack trace:
#0 C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php(1915): woocommerce_abandon_cart_lite->wcal_load_guest_persistent_cart(63000010)
#1 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\class-wp-hook.php(308): woocommerce_abandon_cart_lite->wcal_email_track_links('C:\\Users\\User\\L...')
#2 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\plugin.php(205): WP_Hook->apply_filters('C:\\Users\\User\\L...', Array)
#3 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\template-loader.php(104): apply_filters('template_includ...', 'C:\\Users\\User\\L...')
#4 C:\Users\User\Local Sites\new-ui\app\public\wp-blog-header.php(19): require_once('C:\\Users\\User\\L...')
#5 C:\Users\User\Local Sites\new-ui\app\public\index.php(17): require('C:\\Users\\User\\L...')
#6 {main}
  thrown in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php on line 1950

Note : Same fatal error was appear when  I clicked the link from reminder email and open it to another browser 

**Expected behavior**
No error must be thrown from our plugin.

**Comment by apeksha10** [comment]
After taking the latest git copy, I got the same fatal error when I clicked the cart/checkout link from the reminder email 

[05-Jun-2023 11:29:06 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php:1985
Stack trace:
#0 C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php(1950): woocommerce_abandon_cart_lite->wcal_load_guest_persistent_cart(63000014)
#1 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\class-wp-hook.php(308): woocommerce_abandon_cart_lite->wcal_email_track_links('C:\\Users\\User\\L...')
#2 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\plugin.php(205): WP_Hook->apply_filters('C:\\Users\\User\\L...', Array)
#3 C:\Users\User\Local Sites\new-ui\app\public\wp-includes\template-loader.php(104): apply_filters('template_includ...', 'C:\\Users\\User\\L...')
#4 C:\Users\User\Local Sites\new-ui\app\public\wp-blog-header.php(19): require_once('C:\\Users\\User\\L...')
#5 C:\Users\User\Local Sites\new-ui\app\public\index.php(17): require('C:\\Users\\User\\L...')
#6 {main}
  thrown in C:\Users\User\Local Sites\new-ui\app\public\wp-content\plugins\woocommerce-abandoned-cart\woocommerce-ac.php on line 1985

Hence re-opening this issue

**Comment by apeksha10** [comment]
Closing this issue. Sorry my bad
